### ISSUE TITLE
Program enables `diffEditor.codeLens` on every folder opened, regardless of whether the project contains unity files

### ISSUE THREAD

**Issue by RedBigz** [cblech/unity-file-annotator#3]
This has been happening for ages (and has been annoying my VCS for a while), and I've pinpointed it to this extension. Could you perhaps only set it to change the setting on projects containing .unity and .prefab files? Thanks.

**Comment by cblech** [comment]
Thanks for the Issue and the PR. 
This was just a quick and dirty fix to make the extension work in diff views.
I haven't been working on this extension for a while now and to be honest, I wasn't even aware that people were using it.
Your PR #4 should make it way less annoying, though. I'll merge it and push the update to the Marketplace.

**Comment by cblech** [comment]
Update is pushed to Marketplace
